/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as PublicInvoicesTokenRouteImport } from './routes/public.invoices.$token'
import { Route as ApiPublicPaystackHealthRouteImport } from './routes/api/public/paystack/health'
import { Route as ApiPublicPaystackInitRouteImport } from './routes/api/public/paystack/init'
import { Route as ApiPublicPaystackRefundRouteImport } from './routes/api/public/paystack/refund'
import { Route as ApiPublicPaystackVerifyRouteImport } from './routes/api/public/paystack/verify'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientsRoute,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InvoicesRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicInvoicesTokenRoute = PublicInvoicesTokenRouteImport.update({
  id: '/public/invoices/$token',
  path: '/public/invoices/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackHealthRoute = ApiPublicPaystackHealthRouteImport.update({
  id: '/api/public/paystack/health',
  path: '/api/public/paystack/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackInitRoute = ApiPublicPaystackInitRouteImport.update({
  id: '/api/public/paystack/init',
  path: '/api/public/paystack/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackRefundRoute = ApiPublicPaystackRefundRouteImport.update({
  id: '/api/public/paystack/refund',
  path: '/api/public/paystack/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackVerifyRoute = ApiPublicPaystackVerifyRouteImport.update({
  id: '/api/public/paystack/verify',
  path: '/api/public/paystack/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack/webhook',
    path: '/api/public/paystack/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/quotes': typeof QuotesRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/requests': typeof RequestsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/work': typeof WorkRoute
  '/clients/$id': typeof ClientsIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/public/invoices/$token': typeof PublicInvoicesTokenRoute
  '/api/public/paystack/health': typeof ApiPublicPaystackHealthRoute
  '/api/public/paystack/init': typeof ApiPublicPaystackInitRoute
  '/api/public/paystack/refund': typeof ApiPublicPaystackRefundRoute
  '/api/public/paystack/verify': typeof ApiPublicPaystackVerifyRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/quotes': typeof QuotesRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/requests': typeof RequestsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/work': typeof WorkRoute
  '/clients/$id': typeof ClientsIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/public/invoices/$token': typeof PublicInvoicesTokenRoute
  '/api/public/paystack/health': typeof ApiPublicPaystackHealthRoute
  '/api/public/paystack/init': typeof ApiPublicPaystackInitRoute
  '/api/public/paystack/refund': typeof ApiPublicPaystackRefundRoute
  '/api/public/paystack/verify': typeof ApiPublicPaystackVerifyRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/quotes': typeof QuotesRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/requests': typeof RequestsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/work': typeof WorkRoute
  '/clients/$id': typeof ClientsIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/public/invoices/$token': typeof PublicInvoicesTokenRoute
  '/api/public/paystack/health': typeof ApiPublicPaystackHealthRoute
  '/api/public/paystack/init': typeof ApiPublicPaystackInitRoute
  '/api/public/paystack/refund': typeof ApiPublicPaystackRefundRoute
  '/api/public/paystack/verify': typeof ApiPublicPaystackVerifyRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/dashboard'
    | '/expenses'
    | '/invoices'
    | '/landing'
    | '/login'
    | '/payments'
    | '/projects'
    | '/quotes'
    | '/register'
    | '/reports'
    | '/requests'
    | '/services'
    | '/settings'
    | '/staff'
    | '/work'
    | '/clients/$id'
    | '/invoices/$id'
    | '/projects/$id'
    | '/api/public/health'
    | '/public/invoices/$token'
    | '/api/public/paystack/health'
    | '/api/public/paystack/init'
    | '/api/public/paystack/refund'
    | '/api/public/paystack/verify'
    | '/api/public/paystack/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/dashboard'
    | '/expenses'
    | '/invoices'
    | '/landing'
    | '/login'
    | '/payments'
    | '/projects'
    | '/quotes'
    | '/register'
    | '/reports'
    | '/requests'
    | '/services'
    | '/settings'
    | '/staff'
    | '/work'
    | '/clients/$id'
    | '/invoices/$id'
    | '/projects/$id'
    | '/api/public/health'
    | '/public/invoices/$token'
    | '/api/public/paystack/health'
    | '/api/public/paystack/init'
    | '/api/public/paystack/refund'
    | '/api/public/paystack/verify'
    | '/api/public/paystack/webhook'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/dashboard'
    | '/expenses'
    | '/invoices'
    | '/landing'
    | '/login'
    | '/payments'
    | '/projects'
    | '/quotes'
    | '/register'
    | '/reports'
    | '/requests'
    | '/services'
    | '/settings'
    | '/staff'
    | '/work'
    | '/clients/$id'
    | '/invoices/$id'
    | '/projects/$id'
    | '/api/public/health'
    | '/public/invoices/$token'
    | '/api/public/paystack/health'
    | '/api/public/paystack/init'
    | '/api/public/paystack/refund'
    | '/api/public/paystack/verify'
    | '/api/public/paystack/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ExpensesRoute: typeof ExpensesRoute
  InvoicesRoute: typeof InvoicesRouteWithChildren
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  PaymentsRoute: typeof PaymentsRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  QuotesRoute: typeof QuotesRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  RequestsRoute: typeof RequestsRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  WorkRoute: typeof WorkRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  PublicInvoicesTokenRoute: typeof PublicInvoicesTokenRoute
  ApiPublicPaystackHealthRoute: typeof ApiPublicPaystackHealthRoute
  ApiPublicPaystackInitRoute: typeof ApiPublicPaystackInitRoute
  ApiPublicPaystackRefundRoute: typeof ApiPublicPaystackRefundRoute
  ApiPublicPaystackVerifyRoute: typeof ApiPublicPaystackVerifyRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/invoices/$token': {
      id: '/public/invoices/$token'
      path: '/public/invoices/$token'
      fullPath: '/public/invoices/$token'
      preLoaderRoute: typeof PublicInvoicesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack/health': {
      id: '/api/public/paystack/health'
      path: '/api/public/paystack/health'
      fullPath: '/api/public/paystack/health'
      preLoaderRoute: typeof ApiPublicPaystackHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack/init': {
      id: '/api/public/paystack/init'
      path: '/api/public/paystack/init'
      fullPath: '/api/public/paystack/init'
      preLoaderRoute: typeof ApiPublicPaystackInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack/refund': {
      id: '/api/public/paystack/refund'
      path: '/api/public/paystack/refund'
      fullPath: '/api/public/paystack/refund'
      preLoaderRoute: typeof ApiPublicPaystackRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack/verify': {
      id: '/api/public/paystack/verify'
      path: '/api/public/paystack/verify'
      fullPath: '/api/public/paystack/verify'
      preLoaderRoute: typeof ApiPublicPaystackVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack/webhook': {
      id: '/api/public/paystack/webhook'
      path: '/api/public/paystack/webhook'
      fullPath: '/api/public/paystack/webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClientsRouteChildren {
  ClientsIdRoute: typeof ClientsIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsIdRoute: ClientsIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface InvoicesRouteChildren {
  InvoicesIdRoute: typeof InvoicesIdRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesIdRoute: InvoicesIdRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ExpensesRoute: ExpensesRoute,
  InvoicesRoute: InvoicesRouteWithChildren,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  PaymentsRoute: PaymentsRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  QuotesRoute: QuotesRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  RequestsRoute: RequestsRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  WorkRoute: WorkRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  PublicInvoicesTokenRoute: PublicInvoicesTokenRoute,
  ApiPublicPaystackHealthRoute: ApiPublicPaystackHealthRoute,
  ApiPublicPaystackInitRoute: ApiPublicPaystackInitRoute,
  ApiPublicPaystackRefundRoute: ApiPublicPaystackRefundRoute,
  ApiPublicPaystackVerifyRoute: ApiPublicPaystackVerifyRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
